apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mec
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 30s
    spec:
      containers:
        - image: docker.io/kiemtcb/detection-object:4.5x86@xxx
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: mec